language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libmaxminddb-dev libssl-dev
  - git clone https://git.kore.io/kore.git
  - cd kore && make
  - sudo make install
  - cd -

script: kodev build
